# Generated by Django 5.2.4 on 2025-08-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('github_link', models.URLField(blank=True, null=True)),
                ('demo_link', models.URLField(blank=True, null=True)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='project/')),
                ('preview_video', models.FileField(blank=True, null=True, upload_to='project/videos')),
            ],
        ),
    ]
